FROM debian:jessie
LABEL Maintainer="Nate Bachmeier"
LABEL Course="TIM-8120 Distributed Systems"
LABEL School="NorthCentral University"
LABEL CreatedDate="2019.09.29"

RUN apt-get -y update && apt-get -y install default-jdk nano

