package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, September 29, 2019 6:06:23 PM UTC
*/

public interface HelloOperations 
{
  String sayHello ();
  String greet (String name);
  void shutdown ();
} // interface HelloOperations
